spring.application.name=dao-simplifier-users-app
server.port=8080

spring.r2dbc.url=r2dbc:postgresql://localhost:54329/users_app
spring.r2dbc.username=users_app
spring.r2dbc.password=users_app

spring.liquibase.url=jdbc:postgresql://localhost:54329/users_app
spring.liquibase.user=users_app
spring.liquibase.password=users_app
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

spring.docker.compose.file=compose.yaml
spring.docker.compose.lifecycle-management=start_only

logging.level.org.springframework.r2dbc.core=INFO
